version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: on-failure

  reservation-service:
    image: reservation-service
    container_name: reservation-service
    ports:
      - "8081:8081"
      - "7575:7575"
    depends_on:
      - mongodb
      - discovery-server
      - api-gateway
      - user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: on-failure

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "8082:8082"
      - "6565:6565"
    depends_on:
      - mongodb
      - discovery-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: on-failure

  accommodation-service:
    image: accommodation-service
    container_name: accommodation-service
    ports:
      - "8080:8080"
      - "8585:8585"
    depends_on:
      - mongodb
      - discovery-server
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: on-failure

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
    restart: on-failure

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - mongodb

#  nginx:
#    image: nginx
#    container_name: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - reservation-service
#      - user-service
#      - accommodation-service
#    networks:
#      - mongodb_network_3
