grpc:
  client:
    accommodation-service:
      address: static://localhost:8585
      negotiationType: plaintext
    reservation-service:
      address: static://localhost:7575
      negotiationType: plaintext
    user-service:
      address: static://localhost:6565
      negotiationType: plaintext